### ISSUE TITLE
Acpi errors

### ISSUE THREAD

**Issue by Myles24** [merge/skulls#230]
When compiling coreboot for the x230 from source, I always get an acpi bios error blue screen in windows and the laptop shuts down in linux instead of suspend to ram.  I was wondering if there was a solution to this issue since this error does not occur using skulls.  Thanks for any help.

**Comment by paulmenzel** [comment]
> When compiling coreboot for the x230 from source,

What commit, and what configuration?

> I always get an acpi bios error blue screen in windows

What Microsoft Windows version? What is the exact error code?

> and the laptop shuts down in linux instead of suspend to ram.

Strange. Is it actually suspending, but fails to correctly resume? Log messages would be good to have.

> I was wondering if there was a solution to this issue since this error does not occur using skulls. Thanks for any help.

What version of Skulls? It seems a regression in upstream.

**Comment by explit7** [comment]
Guys, i think, its a bug in new Coreboot Versions. I have an Coreboot 4.15 Image from 11/11/2021 which is working fine in Windows, but Coreboot 4.16 and 4.17 where i get BSOD very in early on Windows Boot.

**Comment by paulmenzel** [comment]
Please give more details, what the Microsoft Windows BSOD ACPI error is.

@explit, it’d be great if you could bisect the commit between coreboot 4.15 and 4.16.

**Comment by Myles24** [comment]
@paulmenzel there is no error code number, the BSOD error is "ACPI_BIOS_ERROR" in Windows.  I am also having that issue in skulls 1.0.5 and I'm not having the issue in 1.0.4.

**Comment by explit7** [comment]
> Please give more details, what the Microsoft Windows BSOD ACPI error is.
> 
> @explit, it’d be great if you could bisect the commit between coreboot 4.15 and 4.16.

Unfortunately i can't post bug report (waiting for the admin approval), but i can attach my dmesg from CoreBoot 4.15 and 4.17
[dmesg_cb415.txt](https://github.com/merge/skulls/files/8934070/dmesg_cb415.txt)
[dmesg_cb417.txt](https://github.com/merge/skulls/files/8934071/dmesg_cb417.txt)

As i said, since CB4.16 there is something broken. As i read, the problem is, that ACPI reserves some memory area, which in Windows is reserved for the system.

This [issue](https://ticket.coreboot.org/issues/327) seems very similar, but the guy is using TianoCore instead of SeaBIOS.
CHanging the line 
`OperationRegion (OPRG, SystemMemory, ASLS, 0x2000)`
to
`OperationRegion (OPRG, SystemMemory, ASLS, 0x1000)`
doesnt fix it for SeaBios, but fix it for TianoCore.

**Comment by Myles24** [comment]
It seems like the issue with Windows BSOD has been resolved with [this](https://github.com/coreboot/coreboot/commit/1233c43a983f0e05cf19c670b790d5e0fe66e2af) coreboot commit.  However, the x230 still won't resume from sleep which will hopefully be resolved in the future.
