### ISSUE TITLE
Add support nvramtool

### ISSUE THREAD

**Issue by khseal** [merge/skulls#43]
nvramtool: CMOS option table not found in coreboot table.  Apparently, the coreboot installed on this system was built without specifying HAVE_OPTION_TABLE.

**Comment by merge** [comment]
What's the issue here? I can run nvramtool without problems and HAVE_OPTION_TABLE is configured, see https://github.com/merge/skulls/blob/master/x230/config-715cb40963#L635

Do have `iomem=relaxed` on your linux cmdline? Since we read /dev/mem this might be necessary but I'm not sure. If not, how can I reproduce your problem?

thanks!

**Comment by khseal** [comment]
I tried running the nvramtool program in lubuntu 18.04. I got this error.

**Comment by merge** [comment]
and how did `cat /proc/cmdline` and `uname -r` look like?

**Comment by khseal** [comment]
BOOT_IMAGE=/boot/vmlinuz-4.15.0-38-generic root=UUID=2b244152-70cc-46a3-8907-2ac4089131ae ro quiet splash vt.handoff=1

**Comment by merge** [comment]
well, as I said. Try to add iomem=relaxed. nvramtool seems to work...

**Comment by khseal** [comment]
Ok, thanks, problem solved
